apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ .Values.gatewayHost }}"
  gateways:
  - {{ .Values.gatewayName }}  
  http:
  - match:
    - uri:
        prefix: {{ .Values.prefixName }}
    route:
    - destination:
        host: {{ .Values.serviceName }}
        port:
          number: {{ .Values.servicePort }}
